### ISSUE TITLE
Arthrobacter model?

### ISSUE THREAD

**Issue by edgingtonn1** [chg60/DEPhT#40]
Would you be interested in creating an Arthrobacter model? ;-)

**Comment by chg60** [comment]
Hi Nick,

I'm potentially interested - the work that led to Figure 8 in the DEPhT paper suggested that their genome architectural features likely make them well-suited for the DEPhT strategy. 

One thing I'd worry about is that at least based on a search of the PATRIC system, there are only a handful of completely sequenced, "reference" Arthrobacter genomes, so even if a model can be trained, it may not work very well in newly sequenced isolates.

If you're able to help me select genomes, I'm willing to try and create a model. I think Cluster AS, AY, and AZ phages are temperate - are there other temperate Arthrobacter phage Clusters or Singletons I should include? Do you have a list of GenBank accessions for Arthrobacter host genomes you think should be included in the model?

Best,

Christian

**Comment by edgingtonn1** [comment]
Hi Christian,

I’d be happy to help!  Are you looking for both lysogens and non-lysogens?  I’ve only used Patric for genome annotation & analysis. I’m on vacation for a week, but I can get a list of Genbank accession numbers, & double-check the Arthrobacter lysogen clusters.

Best,
- Nick

**************************************
Nicholas Edgington, Ph.D.
Professor
B.S. Biotech Program Coordinator

Southern Connecticut State University
501 Crescent St.<x-apple-data-detectors://1/1>
Department of Biology, SCI 311E
New Haven, CT 06515

PH:   1-203-392-6219<tel:1-203-392-6219>
FAX: 1-203-392-5364<tel:1-203-392-5364>
**************************************

On Jun 7, 2023, at 3:38 PM, Christian Gauthier ***@***.***> wrote:

Hi Nick,

I'm potentially interested - the work that led to Figure 8 in the DEPhT paper suggested that their genome architectural features likely make them well-suited for the DEPhT strategy.

One thing I'd worry about is that at least based on a search of the PATRIC system, there are only a handful of completely sequenced, "reference" Arthrobacter genomes, so even if a model can be trained, it may not work very well in newly sequenced isolates.

If you're able to help me select genomes, I'm willing to try and create a model. I think Cluster AS, AY, and AZ phages are temperate - are there other temperate Arthrobacter phage Clusters or Singletons I should include? Do you have a list of GenBank accessions for Arthrobacter host genomes you think should be included in the model?

Best,

Christian

**Comment by chg60** [comment]
Hi Nick,

Any progress on genome selection for your Arthrobacter model?

-C

**Comment by chg60** [comment]
Closing this issue for now. @edgingtonn1 feel free to re-open when and if you have the bandwidth to work on this. Thanks!

-C
