### ISSUE TITLE
Installation of DEPht

### ISSUE THREAD

**Issue by aamaniii0** [chg60/DEPhT#42]
I have been trying to install DEPhT, however, it seems to be an issue of conflicting dependencies. When I looked into it more this is what appeared:

Cannot install depht==1.0.0, depht==1.0.1, depht==1.0.2, depht==1.1.1, depht==1.1.2, depht==1.1.3, depht==1.1.4, depht==1.1.5, depht==1.1.6, depht==1.1.7, depht==1.1.8 and depht==1.2.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    depht 1.2.0 depends on scipy~=1.7.0
    depht 1.1.8 depends on scipy~=1.7.0
    depht 1.1.7 depends on scipy~=1.7.0
    depht 1.1.6 depends on scipy~=1.7.0
    depht 1.1.5 depends on scipy~=1.7.0
    depht 1.1.4 depends on scipy~=1.7.0
    depht 1.1.3 depends on scipy~=1.7.0
    depht 1.1.2 depends on scipy~=1.7.0
    depht 1.1.1 depends on scipy~=1.7.0
    depht 1.0.2 depends on scipy~=1.7.0
    depht 1.0.1 depends on scipy~=1.7.0
    depht 1.0.0 depends on scipy~=1.7.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

How can I solve this and install DEPhT?

**Comment by chg60** [comment]
I've removed the scipy dependency altogether and updated the PyPI/conda package build specs. Version 1.2.1 should work just fine.

`conda create -n depht-env -c conda-forge -c bioconda -c laa89 depht -y`

Works on the MacOS and Linux systems I have at my disposal. It may take up to 5-10 minutes to resolve the dependencies, but does so without errors.

I'm closing the issue for now, but feel free to re-open if you encounter further build issues.
