### ISSUE TITLE
Problems running DEPhT

### ISSUE THREAD

**Issue by ntmscope** [chg60/DEPhT#45]
Hi, 

I installed DEPhT twice (both manually and according to your recommendations). However, it won't run on a test fasta file with the following command:

depht test.fasta output

Giving the following error message:

Traceback (most recent call last):
  File "/home/user/miniconda3/envs/depht-env/bin/depht", line 8, in <module>
    sys.exit(main())
  File "/home/user/miniconda3/envs/depht-env/lib/python3.9/site-packages/depht/__main__.py", line 235, in main
    annotate_record(record, annotate_dir)
  File "/home/user/miniconda3/envs/depht-env/lib/python3.9/site-packages/depht/functions/annotation.py", line 180, in annotate_record
    for feature in parse_prodigal(prodigal_out):
  File "/home/user/miniconda3/envs/depht-env/lib/python3.9/site-packages/depht/functions/annotation.py", line 65, in parse_prodigal
    ftr = SeqFeature(location=FeatureLocation(start - 1, end),
TypeError: __init__() got an unexpected keyword argument 'strand'

Can you make anything of this? Any help is highly appreciated!

**Comment by chg60** [comment]
Hello!

Thanks for your interest in DEPhT. This looks like an issue related to some changes in the BioPython library that happened relatively recently. I’ll do my best to resolve this issue today.

Thank you in advance for your patience and understanding.

Best,

Christian

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: ntmscope ***@***.***>
Sent: Tuesday, January 9, 2024 5:10:28 AM
To: chg60/DEPhT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chg60/DEPhT] Problems running DEPhT (Issue #45)


Hi,

I installed DEPhT twice (both manually and according to your recommendations). However, it won't run on a test fasta file with the following command:

depht test.fasta output

Giving the following error message:

Traceback (most recent call last):
File "/home/user/miniconda3/envs/depht-env/bin/depht", line 8, in
sys.exit(main())
File "/home/user/miniconda3/envs/depht-env/lib/python3.9/site-packages/depht/main.py", line 235, in main
annotate_record(record, annotate_dir)
File "/home/user/miniconda3/envs/depht-env/lib/python3.9/site-packages/depht/functions/annotation.py", line 180, in annotate_record
for feature in parse_prodigal(prodigal_out):
File "/home/user/miniconda3/envs/depht-env/lib/python3.9/site-packages/depht/functions/annotation.py", line 65, in parse_prodigal
ftr = SeqFeature(location=FeatureLocation(start - 1, end),
TypeError: init() got an unexpected keyword argument 'strand'

Can you make anything of this? Any help is highly appreciated!

**Comment by chg60** [comment]
I did a little [digging](https://github.com/biopython/biopython/issues/4563) and found that BioPython version 1.82 introduces this bug. I'll patch the DEPhT this week with a more complete fix but if you want a quick fix that will let you run DEPhT today, you can run these commands with your conda environment active:

```
pip uninstall biopython
pip install biopython==1.81
```

This will downgrade your BioPython to the last known working version. Then, when you run DEPhT, you will see a DeprecationWarning instead of the program crashing.

The next release of DEPhT should be uploaded this week.

**Comment by ntmscope** [comment]
Dear Christian, 

thanks a lot for the rapid reply. I will try both :)

Best regards
Nils

**Comment by peterjc** [comment]
@chg60 this is *not* a bug in Biopython 1.82.

This is functionality was deprecated in Biopython 1.80 and removed in 1.82 (passing strand as an argument to the SeqFeature initialisation). You should have been getting deprecation warnings if tested on Biopython 1.80 or 1.81.

The issue you linked to was about the strand attribute.

See fix for DEPhT in #46, which will work on current Biopython and older releases too.

**Comment by chg60** [comment]
Testing reveals several other locations in the repo that use feature.strand instead of feature.location.strand.

Systematically updating these as well to quash all Biopython DeprecationWarnings.

**Comment by peterjc** [comment]
I hoped that was it, but didn't see any test framework and didn't attempt to run this localy.

**Comment by chg60** [comment]
DEPhT v1.2.2 should resolve this issue. Thanks again @peterjc

**Comment by peterjc** [comment]
I see some of the other fixes were required on Biopython 1.82 due to the bug https://github.com/biopython/biopython/issues/4563 - touch wood you're OK on Biopython 1.82 and 1.83 now :)
