### ISSUE TITLE
Is it suitable for metagenome-assembled genomes (MAGs)?

### ISSUE THREAD

**Issue by WoCer2019** [chg60/DEPhT#48]
Hi,

Nice tool!

Is this tool suitable for the identification of prophages from MAGs?

Thanks!

WarrenYates

**Comment by chg60** [comment]
If you’re dealing with contigs of significant length (20,000+ bases), in species for which DEPhT models have been trained - yes! Unfortunately, I have not had the time to train any additional models beyond the ones we published, so if your MAGs are from diverse, non-Actinobacterial species you may be better served by using other tools like VorSorter2 or VIBRANT.

Best,

Christian

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: WoCer2019 ***@***.***>
Sent: Saturday, October 12, 2024 5:11:32 AM
To: chg60/DEPhT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chg60/DEPhT] Is it suitable for metagenome-assembled genomes (MAGs)? (Issue #48)


Hi,

Nice tool!

Is this tool suitable for the identification of prophages from MAGs?

Thanks!

WarrenYates

**Comment by WoCer2019** [comment]
Thanks!
